### ISSUE TITLE
Stopped working in Sublime Text

### ISSUE THREAD

**Issue by Boscop** [codota/TabNine#325]
- OS version: Manjaro	
 - Editor: sublime
 - Editor version: 3.2.2, build 3211
 - Programming language: Rust
 - TabNine extension version: no idea

**Issue Details:**
TabNine stopped working. Usually when that happens, disabling and re-enabling the package makes it work again, or restarting Sublime, but this time it didnt.
So I checked the console:

```
Tabnine: starting version /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.33
Exception while interacting with Tabnine subprocess: No JSON object could be decoded
Tabnine: starting version /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.33
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/me/.config/sublime-text-3/Packages/Tabnine/TabNine.py", line 28, in <module>
    capabilities["enabled_features"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by boaz-codota** [comment]
Looking into that. 

Thanks for reporting the issue!

**Comment by boaz-codota** [comment]
Could you report what versions of TabNine you have locally? 

The versions are the folders you can see in:
`/home/me/.config/sublime-text-3/Packages/Tabnine/binaries/`

And (just to make sure,) have you tried closing & reopening Sublime Text?

**Comment by dimacodota** [comment]
Hi @Boscop , can you please check if you have other Tabnine processes running, maybe from another IDE? If so please close and reopen them.

**Comment by Boscop** [comment]
@boaz-codota 
> $ ls /home/me/.config/sublime-text-3/Packages/Tabnine/binaries/
> 0.0.1  3.2.84  3.3.34

> And (just to make sure,) have you tried closing & reopening Sublime Text?

yes, like I wrote above :)

> can you please check if you have other Tabnine processes running, maybe from another IDE? If so please close and reopen them.

I don't have any other IDEs, I only use Sublime.

**Comment by Boscop** [comment]
Hm, it seems I have a TabNine zombie process. Why?

And how to kill it?

![image](https://user-images.githubusercontent.com/535593/104926698-c7ffc680-59a0-11eb-91c5-4a344fe8b4bd.png)

**Comment by dimacodota** [comment]
can you please follow the steps below and send us the Tabnine log files?  

 - go to Tabnine's user settings in sublime and add the `log_file_path` property, It should contain an absolute path.
 - restart Sublime and send us the log file.
 
Thanks

**Comment by Boscop** [comment]
I wrote this inside `/home/me/.config/sublime-text-3/Packages/User/TabNine.sublime-settings`:
```json
{
	"log_file_path": "/home/me/Documents/tabnine.log",
}
```
I restarted Sublime. This log file was not created but now TabNine works again.
In the console it logged:
```
reloading plugin Tabnine.TabNine
Tabnine: starting version /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34
```

I'm still curious what had caused tabnine to become a zombie..

**Comment by dimacodota** [comment]
> I wrote this inside `/home/me/.config/sublime-text-3/Packages/User/TabNine.sublime-settings`:
> 
> ```json
> {
> 	"log_file_path": "/home/me/Documents/tabnine.log",
> }
> ```
> 
> I restarted Sublime. This log file was not created but now TabNine works again.
> In the console it logged:
> 
> ```
> reloading plugin Tabnine.TabNine
> Tabnine: starting version /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34
> ```
> 
> I'm still curious what had caused tabnine to become a zombie..
> 
> Btw, can I delete the old versions, the folder `0.0.1` and `3.2.84` in `/home/me/.config/sublime-text-3/Packages/Tabnine/binaries/`?

the config file should be in a valid JSON format, can you please remove the comma (",") and reload Sublime?

**Comment by Boscop** [comment]
Now it wrote the log file:
```
[2021-01-18T16:40:50.979786479+01:00][INFO][262437 main][TabNine][Some("tabnine/frontend/src/main.rs")][Some(430)] /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34/x86_64-unknown-linux-musl/TabNine --client sublime --log-file-path /home/me/Documents/tabnine.log --client-metadata clientVersion=3211 pluginVersion=Unknown nativeAutoComplete=False ide-restart-counter=0
[2021-01-18T16:40:50.979842466+01:00][INFO][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(174)] token path: /home/me/.config/TabNine/tabnine.token
[2021-01-18T16:40:50.979862229+01:00][INFO][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(161)] Failed to read token file, user cannot be identified: No such file or directory (os error 2)
[2021-01-18T16:40:50.980052924+01:00][INFO][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(310)] Start watching token file
[2021-01-18T16:40:50.980073131+01:00][WARN][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(409)] No user token available
[2021-01-18T16:40:50.980127403+01:00][INFO][262437 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/bootstrapper_conf.prefs.json")
[2021-01-18T16:40:50.980153229+01:00][WARN][262437 main][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-18T16:40:50.980173059+01:00][INFO][262437 main][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(91)] config is BootstrapConfig { bootstrapper_enabled: true, api_endpoint: "https://api.tabnine.com/experiments/register/v2", registration_interval_seconds: 3600, bark_interval_seconds: 2, force_version: None }
[2021-01-18T16:40:50.981192156+01:00][INFO][262437 main][watchdog_api::wd_client][Some("shared/wd_api/src/wd_client.rs")][Some(64)] Initializing watchdog client...
[2021-01-18T16:40:51.169026387+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
[2021-01-18T16:40:51.169128621+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/tabnine_version_3.3.34.prefs.json")
[2021-01-18T16:40:51.169209633+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/bootstrapper_conf.prefs.json")
[2021-01-18T16:40:51.169234347+01:00][WARN][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-18T16:40:51.169257049+01:00][INFO][262437 bs_main_rlp][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(191)] trying to start tabnine version Some("3.3.34")
[2021-01-18T16:40:51.169275792+01:00][INFO][262437 bs_main_rlp][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(267)] spawning tabnine with args ["/home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34/x86_64-unknown-linux-musl/TabNine", "--client", "sublime", "--log-file-path", "/home/me/Documents/tabnine.log", "--client-metadata", "clientVersion=3211", "pluginVersion=Unknown", "nativeAutoComplete=False", "ide-restart-counter=0", "--no_bootstrap"]
[2021-01-18T16:40:51.169421797+01:00][INFO][262437 bs_main_rlp][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(271)] started tabnine process pid 262478 version Some("3.3.34"), desired version was Some("3.3.34") this version is Some("3.3.34")
[2021-01-18T16:40:51.169502703+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
[2021-01-18T16:40:51.170196176+01:00][INFO][262478 main][TabNine][Some("tabnine/frontend/src/main.rs")][Some(430)] /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34/x86_64-unknown-linux-musl/TabNine --client sublime --log-file-path /home/me/Documents/tabnine.log --client-metadata clientVersion=3211 pluginVersion=Unknown nativeAutoComplete=False ide-restart-counter=0 --no_bootstrap
[2021-01-18T16:40:51.170248166+01:00][INFO][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(174)] token path: /home/me/.config/TabNine/tabnine.token
[2021-01-18T16:40:51.170262288+01:00][INFO][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(161)] Failed to read token file, user cannot be identified: No such file or directory (os error 2)
[2021-01-18T16:40:51.170456349+01:00][INFO][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(310)] Start watching token file
[2021-01-18T16:40:51.170477706+01:00][WARN][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(409)] No user token available
[2021-01-18T16:40:51.170610959+01:00][INFO][262478 main][watchdog_api::wd_client][Some("shared/wd_api/src/wd_client.rs")][Some(64)] Initializing watchdog client...
[2021-01-18T16:40:51.174429145+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
[2021-01-18T16:40:51.427277765+01:00][INFO][262478 lunar settings update thread (Remote)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(508)] lunar settings update thread started (Remote)
[2021-01-18T16:40:51.427341977+01:00][INFO][262478 lunar settings update thread (Remote)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(514)] lunar settings update thread exiting (Remote)
[2021-01-18T16:40:51.427301168+01:00][INFO][262478 model hash update thread][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(618)] model hash updater starting
[2021-01-18T16:40:51.427288143+01:00][INFO][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
[2021-01-18T16:40:51.427505015+01:00][INFO][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/message_shown_timestamp_default.prefs.json")
[2021-01-18T16:40:51.427534484+01:00][WARN][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-18T16:40:51.427563083+01:00][INFO][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/experiment_converged_default.prefs.json")
[2021-01-18T16:40:51.427581386+01:00][WARN][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
[2021-01-18T16:40:51.427686244+01:00][INFO][262478 lunar settings update thread (Local)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(508)] lunar settings update thread started (Local)
[2021-01-18T16:40:51.427740153+01:00][INFO][262478 lunar settings update thread (Local)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(514)] lunar settings update thread exiting (Local)
[2021-01-18T16:40:51.428102076+01:00][INFO][262478 main][frontend][Some("tabnine/frontend/src/lib.rs")][Some(100)] Started.
[2021-01-18T16:40:51.429237585+01:00][INFO][262550 main][locking][Some("shared/locking/src/lib.rs")][Some(78)] Trying to lock: "/home/me/.config/TabNine/3.3.34/TabNine-deep-local.lock"
[2021-01-18T16:40:51.450044958+01:00][INFO][262550 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
[2021-01-18T16:40:51.528692896+01:00][INFO][262478 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
[2021-01-18T16:40:51.528727264+01:00][INFO][262437 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
[2021-01-18T16:40:51.628854004+01:00][INFO][262478 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
[2021-01-18T16:40:51.628857143+01:00][INFO][262437 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
[2021-01-18T16:40:52.365379865+01:00][INFO][262550 main][TabNine_deep_local][Some("deep/lunar_endpoints/src/bin/TabNine-deep-local.rs")][Some(161)] TabNine-deep-local is already running, responding with existing port
[2021-01-18T16:40:52.366384337+01:00][INFO][262478 TabNine deep local exit wait thread][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(717)] TabNine-deep-local exited with status exit code: 0
[2021-01-18T16:40:52.924783856+01:00][INFO][262437 bs_main_rlp][bootstrapper::bootstrapper_lib][Some("tabnine/bootstrapper/src/bootstrapper_lib.rs")][Some(257)] current version is Some(Version { major: 3, minor: 3, patch: 34, pre: [], build: [] }), spawned version is Some(Version { major: 3, minor: 3, patch: 34, pre: [], build: [] }), remote version is Version { major: 3, minor: 3, patch: 34, pre: [], build: [] }
[2021-01-18T16:40:53.149000705+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
[2021-01-18T16:40:53.149044541+01:00][INFO][262437 bs_main_rlp][bootstrapper::bootstrapper_lib][Some("tabnine/bootstrapper/src/bootstrapper_lib.rs")][Some(330)] don't need to upgrade
```

But everything seems back to normal.
No clue about why it caused the process to become a zombie..
Could it be caused by putting the laptop into sleep mode?

---

Btw, can I delete the old versions, the folder `0.0.1` and `3.2.84` in `/home/me/.config/sublime-text-3/Packages/Tabnine/binaries/`?

**Comment by dimacodota** [comment]
> Now it wrote the log file:
> 
> ```
> [2021-01-18T16:40:50.979786479+01:00][INFO][262437 main][TabNine][Some("tabnine/frontend/src/main.rs")][Some(430)] /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34/x86_64-unknown-linux-musl/TabNine --client sublime --log-file-path /home/me/Documents/tabnine.log --client-metadata clientVersion=3211 pluginVersion=Unknown nativeAutoComplete=False ide-restart-counter=0
> [2021-01-18T16:40:50.979842466+01:00][INFO][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(174)] token path: /home/me/.config/TabNine/tabnine.token
> [2021-01-18T16:40:50.979862229+01:00][INFO][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(161)] Failed to read token file, user cannot be identified: No such file or directory (os error 2)
> [2021-01-18T16:40:50.980052924+01:00][INFO][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(310)] Start watching token file
> [2021-01-18T16:40:50.980073131+01:00][WARN][262437 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(409)] No user token available
> [2021-01-18T16:40:50.980127403+01:00][INFO][262437 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/bootstrapper_conf.prefs.json")
> [2021-01-18T16:40:50.980153229+01:00][WARN][262437 main][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
> [2021-01-18T16:40:50.980173059+01:00][INFO][262437 main][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(91)] config is BootstrapConfig { bootstrapper_enabled: true, api_endpoint: "https://api.tabnine.com/experiments/register/v2", registration_interval_seconds: 3600, bark_interval_seconds: 2, force_version: None }
> [2021-01-18T16:40:50.981192156+01:00][INFO][262437 main][watchdog_api::wd_client][Some("shared/wd_api/src/wd_client.rs")][Some(64)] Initializing watchdog client...
> [2021-01-18T16:40:51.169026387+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
> [2021-01-18T16:40:51.169128621+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/tabnine_version_3.3.34.prefs.json")
> [2021-01-18T16:40:51.169209633+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/bootstrapper_conf.prefs.json")
> [2021-01-18T16:40:51.169234347+01:00][WARN][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
> [2021-01-18T16:40:51.169257049+01:00][INFO][262437 bs_main_rlp][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(191)] trying to start tabnine version Some("3.3.34")
> [2021-01-18T16:40:51.169275792+01:00][INFO][262437 bs_main_rlp][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(267)] spawning tabnine with args ["/home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34/x86_64-unknown-linux-musl/TabNine", "--client", "sublime", "--log-file-path", "/home/me/Documents/tabnine.log", "--client-metadata", "clientVersion=3211", "pluginVersion=Unknown", "nativeAutoComplete=False", "ide-restart-counter=0", "--no_bootstrap"]
> [2021-01-18T16:40:51.169421797+01:00][INFO][262437 bs_main_rlp][TabNine::bootstrap_support][Some("tabnine/frontend/src/bootstrap_support.rs")][Some(271)] started tabnine process pid 262478 version Some("3.3.34"), desired version was Some("3.3.34") this version is Some("3.3.34")
> [2021-01-18T16:40:51.169502703+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
> [2021-01-18T16:40:51.170196176+01:00][INFO][262478 main][TabNine][Some("tabnine/frontend/src/main.rs")][Some(430)] /home/me/.config/sublime-text-3/Packages/Tabnine/lib/../binaries/3.3.34/x86_64-unknown-linux-musl/TabNine --client sublime --log-file-path /home/me/Documents/tabnine.log --client-metadata clientVersion=3211 pluginVersion=Unknown nativeAutoComplete=False ide-restart-counter=0 --no_bootstrap
> [2021-01-18T16:40:51.170248166+01:00][INFO][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(174)] token path: /home/me/.config/TabNine/tabnine.token
> [2021-01-18T16:40:51.170262288+01:00][INFO][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(161)] Failed to read token file, user cannot be identified: No such file or directory (os error 2)
> [2021-01-18T16:40:51.170456349+01:00][INFO][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(310)] Start watching token file
> [2021-01-18T16:40:51.170477706+01:00][WARN][262478 main][auth::user][Some("tabnine/auth/src/user.rs")][Some(409)] No user token available
> [2021-01-18T16:40:51.170610959+01:00][INFO][262478 main][watchdog_api::wd_client][Some("shared/wd_api/src/wd_client.rs")][Some(64)] Initializing watchdog client...
> [2021-01-18T16:40:51.174429145+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
> [2021-01-18T16:40:51.427277765+01:00][INFO][262478 lunar settings update thread (Remote)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(508)] lunar settings update thread started (Remote)
> [2021-01-18T16:40:51.427341977+01:00][INFO][262478 lunar settings update thread (Remote)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(514)] lunar settings update thread exiting (Remote)
> [2021-01-18T16:40:51.427301168+01:00][INFO][262478 model hash update thread][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(618)] model hash updater starting
> [2021-01-18T16:40:51.427288143+01:00][INFO][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
> [2021-01-18T16:40:51.427505015+01:00][INFO][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/message_shown_timestamp_default.prefs.json")
> [2021-01-18T16:40:51.427534484+01:00][WARN][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
> [2021-01-18T16:40:51.427563083+01:00][INFO][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/experiment_converged_default.prefs.json")
> [2021-01-18T16:40:51.427581386+01:00][WARN][262478 main][defaults][Some("shared/defaults/src/lib.rs")][Some(118)] had an error deserializing object Os { code: 2, kind: NotFound, message: "No such file or directory" }
> [2021-01-18T16:40:51.427686244+01:00][INFO][262478 lunar settings update thread (Local)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(508)] lunar settings update thread started (Local)
> [2021-01-18T16:40:51.427740153+01:00][INFO][262478 lunar settings update thread (Local)][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(514)] lunar settings update thread exiting (Local)
> [2021-01-18T16:40:51.428102076+01:00][INFO][262478 main][frontend][Some("tabnine/frontend/src/lib.rs")][Some(100)] Started.
> [2021-01-18T16:40:51.429237585+01:00][INFO][262550 main][locking][Some("shared/locking/src/lib.rs")][Some(78)] Trying to lock: "/home/me/.config/TabNine/3.3.34/TabNine-deep-local.lock"
> [2021-01-18T16:40:51.450044958+01:00][INFO][262550 main][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
> [2021-01-18T16:40:51.528692896+01:00][INFO][262478 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
> [2021-01-18T16:40:51.528727264+01:00][INFO][262437 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
> [2021-01-18T16:40:51.628854004+01:00][INFO][262478 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
> [2021-01-18T16:40:51.628857143+01:00][INFO][262437 thread][global_config::global_config][Some("shared/global_config/src/global_config.rs")][Some(922)] config path: /home/me/.config/TabNine/tabnine_config.json
> [2021-01-18T16:40:52.365379865+01:00][INFO][262550 main][TabNine_deep_local][Some("deep/lunar_endpoints/src/bin/TabNine-deep-local.rs")][Some(161)] TabNine-deep-local is already running, responding with existing port
> [2021-01-18T16:40:52.366384337+01:00][INFO][262478 TabNine deep local exit wait thread][lunar_connection][Some("tabnine/lunar_connection/src/lib.rs")][Some(717)] TabNine-deep-local exited with status exit code: 0
> [2021-01-18T16:40:52.924783856+01:00][INFO][262437 bs_main_rlp][bootstrapper::bootstrapper_lib][Some("tabnine/bootstrapper/src/bootstrapper_lib.rs")][Some(257)] current version is Some(Version { major: 3, minor: 3, patch: 34, pre: [], build: [] }), spawned version is Some(Version { major: 3, minor: 3, patch: 34, pre: [], build: [] }), remote version is Version { major: 3, minor: 3, patch: 34, pre: [], build: [] }
> [2021-01-18T16:40:53.149000705+01:00][INFO][262437 bs_main_rlp][defaults][Some("shared/defaults/src/lib.rs")][Some(102)] getting value from path Ok("/home/me/.config/TabNine/defaults/active_experiment.prefs.json")
> [2021-01-18T16:40:53.149044541+01:00][INFO][262437 bs_main_rlp][bootstrapper::bootstrapper_lib][Some("tabnine/bootstrapper/src/bootstrapper_lib.rs")][Some(330)] don't need to upgrade
> ```
> 
> But everything seems back to normal.
> No clue about why it caused the process to become a zombie..
> Could it be caused by putting the laptop into sleep mode?
> 
> Btw, can I delete the old versions, the folder `0.0.1` and `3.2.84` in `/home/me/.config/sublime-text-3/Packages/Tabnine/binaries/`?

yes, you can remove the old version.

regarding the zombie process, we are still investigating the issue
