### ISSUE TITLE
Tabnine throws exceptions

### ISSUE THREAD

**Issue by zrma** [codota/TabNine#387]
**please complete the following information:**	
 - OS version: Windows 10 20H2(build 19042.928)
 - Editor: GoLand 2021.1.1 (runtime version: 11.0.10+9-b1341.41 amd64)
 - Editor version: 2021.1.1
 - Programming language: golang
 - TabNine extension version: 0.3.5
 - Engine version (could be located within Tabnine Hub): 3.3.115-26

**Issue Details:**

```plaintext
Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:58)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:43)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:23)
	at com.tabnine.lifecycle.BinaryStateService.updateState(BinaryStateService.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I attach IDE logs and tabnine's logs

[log_file.zip](https://github.com/codota/TabNine/files/6371385/log_file.zip)

**Comment by kinkkong** [comment]
Same here

**Comment by shaiahr** [comment]
Hi @zrma, @kinkkong 
Can you please restart your IDE, open Tabnine's hub, disable the cloud completions:
![image](https://user-images.githubusercontent.com/26132852/116517684-f5310e80-a8d7-11eb-9ead-b0a245278d1c.png)
and see if the problem persists?

**Comment by shaiahr** [comment]
I don't think anything in the new plugin can explain that.
If the issue happens again please send me your IDE and tabnine logs.

Thanks
Shai

**Comment by zrma** [comment]
> I don't think anything in the new plugin can explain that.
> If the issue happens again please send me your IDE and tabnine logs.
> 
> Thanks
> Shai

Hi.
Since I wrote the comment earlier https://github.com/codota/TabNine/issues/387#issuecomment-829089272 ,
the problem occurred again after a certain period of time.

So I did it like you told me to do. https://github.com/codota/TabNine/issues/387#issuecomment-829014059
I disabled cloud completions.

and some minutes later, then the same problem occurred again.
so I attached new log files.

[log_file.zip](https://github.com/codota/TabNine/files/6398043/log_file.zip)

Thank you for your help.

**Comment by shaiahr** [comment]
@zrma we're unable to reproduce this on our windows machine.
Can you say what you're doing when this error happens? Do you see these errors only after typing code or even if you just start GoLand and do nothing?
Other then seeing this in the log, what are the effects on your experience? Does Tabnine still show suggestions?

**Comment by zrma** [comment]
> @zrma we're unable to reproduce this on our windows machine.
> Can you say what you're doing when this error happens? Do you see these errors only after typing code or even if you just start GoLand and do nothing?
> Other then seeing this in the log, what are the effects on your experience? Does Tabnine still show suggestions?

@shaiahr 

It happens when I write some code and refactor in a normal way.

It doesn't happen if I don't do anything.
It only happens when I write the code.

Then, TabNine does not work properly.
And it works again after a certain period of time.

It's as like that the process dies and comes back up.
And even if there is no crash report like that, auto completion often switches working and not working repeatedly.

Thanks.
