### ISSUE TITLE
Tabnine run not right

### ISSUE THREAD

**Issue by IRediTOTO** [codota/TabNine#444]
**please complete the following information:**	
 - OS version: Win 10
 - Editor: vscode
 - Editor version: newest	
 - Programming language: js, ts, react
 - TabNine extension version: newest
 - Engine version (could be located within Tabnine Hub):  newest

**Issue Details:**
I don't know what is issue, just take longgg time to save a tab. Let's take a look if you can :) 
```
ERR Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at c:\Users\godde\.vscode\extensions\tabnine.tabnine-vscode-3.4.22\out\extension.js:17:43569
    at t.default (c:\Users\godde\.vscode\extensions\tabnine.tabnine-vscode-3.4.22\out\extension.js:17:43593)
    at d.fire (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at D.$acceptDirtyStateChanged (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:148126)
    at D.$acceptModelSaved (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:147869)
    at h._doInvokeHandler (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
    at h._invokeHandler (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
    at h._receiveRequest (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11159)
    at h._receiveOneMessage (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
    at c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
    at d.fire (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at c.fire (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
    at c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
    at d.fire (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at c.fire (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
    at r._receiveMessage (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
    at c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
    at d.fire (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
    at v.acceptChunk (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
    at c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
    at Socket.w (c:\Users\godde\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

![image](https://user-images.githubusercontent.com/15695252/130316104-dd3cbcbf-601e-477d-b752-39fe422077d9.png)
![image](https://user-images.githubusercontent.com/15695252/130316115-7d16a050-d17f-4302-9a7d-14426de5e76e.png)
![image](https://user-images.githubusercontent.com/15695252/130316128-b110e611-4e17-4a20-be07-4a6fe9947c91.png)
![image](https://user-images.githubusercontent.com/15695252/130316133-fc0d1dc8-565c-450f-8984-5c3a24157cab.png)
![image](https://user-images.githubusercontent.com/15695252/130316151-edda1c59-af9f-4e9f-8683-717283160772.png)
```
ERR Extension host terminated unexpectedly. The following extensions were running: aaron-bond.better-comments, vscode.extension-editing, vscode.typescript-language-features, VisualStudioExptTeam.vscodeintellicode, vscode.microsoft-authentication, ms-vscode.js-debug, vscode.debug-auto-launch, vscode.git, christian-kohler.path-intellisense, formulahendry.auto-close-tag, formulahendry.auto-rename-tag, PKief.material-icon-theme, TabNine.tabnine-vscode, vincaslt.highlight-matching-tag, vscode.github-authentication, vscode.configuration-editing, vscode.json-language-features, vscode.npm, eg2.vscode-npm-script, richie5um2.vscode-sort-json, Prisma.prisma, eamodio.gitlens, vscode.github, vscode.emmet, vscode.merge-conflict, ms-vscode-remote.remote-wsl-recommender, bradlc.vscode-tailwindcss, dbaeumer.vscode-eslint, esbenp.prettier-vscode, Gruntfuggly.todo-tree
```

gz#5405

**Comment by bilucodota** [comment]
Hi @IRediTOTO is it happening only wit Tabnine installed?

**Comment by IRediTOTO** [comment]
> Hi @IRediTOTO is it happening only wit Tabnine installed?

I think problem come from Prisma extendtion. I turn it off and everything run fine. :)
