### ISSUE TITLE
Tabnine in goland occured fatal error

### ISSUE THREAD

**Issue by zouyonghe** [codota/TabNine#517]
**please complete the following information:**	
 - OS version: [e.g. Win 10, Mac Catalina]
Darwin budingdeMacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64	
 - Editor: [e.g. vscode, intelij, sublime]	
Goland 
 - Editor version:	
2021.3.3
 - Programming language: [e.g. js, ts, c++]	
 Go
 - TabNine extension version:
 - 0.5.22
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

Tabnine is not able to function properly. Contact support@tabnine.com

com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:69)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:44)
	at com.tabnine.prediction.CompletionFacade.retrieveCompletions(CompletionFacade.java:77)
	at com.tabnine.prediction.CompletionFacade.lambda$retrieveCompletions$0(CompletionFacade.java:34)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$1(ApplicationUtil.java:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.application.ex.ApplicationUtil.lambda$runWithCheckCanceled$2(ApplicationUtil.java:41)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:263)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

gz#12299

**Comment by maya-tabnine** [comment]
Hi can you attach your Tabnine log?
To get Tabnine's log, in a JetBrains ide, please open: Help -> Edit Custom Properties...
and insert:
`TABNINE_LOG_FILE_PATH=<some path to a file>`
Restart your IDE and use it for a few minutes to let the logs flow in.
Then, you'll find a file named filename_rCURRENT.ext-<pid> in the given directory. 

Also, what is your Tabnine engine version? Can you reach Tabnine hub and check?

**Comment by zouyonghe** [comment]
I just clicked the tabnine button in my ide, but no page opened.

There are two errors found in my ide, but in my log file path, there is  nothing found.

Here is the errrors.
1.
com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:69)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:44)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:22)
	at com.tabnine.capabilities.CapabilitiesService.fetchCapabilities(CapabilitiesService.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

2.
com.tabnine.binary.exceptions.BinaryCannotRecoverException
	at com.tabnine.binary.BinaryProcessRequesterProvider.onDead(BinaryProcessRequesterProvider.java:69)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:44)
	at com.tabnine.binary.BinaryRequestFacade.executeRequest(BinaryRequestFacade.java:22)
	at com.tabnine.lifecycle.BinaryNotificationsLifecycle$poll$1.run(BinaryNotificationsLifecycle.kt:26)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by zouyonghe** [comment]
The tabnine engine version is 4.1.3.

Your method of reinstall tabnine solved my problem, thanks a lot!
