### ISSUE TITLE
Sign in button doesn't do anything for VSCode

### ISSUE THREAD

**Issue by Diederikjh** [codota/TabNine#599]
**please complete the following information:**	
 - OS version: Ubuntu 22.04.2
 - Editor: VSCode
 - Editor version: 1.77.3
 - Programming language:  Python 
 - TabNine extension version: 3.6.44
 - Engine version (could be located within Tabnine Hub):  4.4.281-60

**Issue Details:**

Hi, I've just installed the tabnine plugin in on VSCode.  It restarted the editor.  I've setup a trail with my google account on the website, but I can't seem to sign in using the VSCode extension.

Things I've tried:  Click on tabnine's settings. Then sign in: nothing happens when I click on it in top right corner.

On the accounts button, I see there is a notification saying "Sign in to use tabnine AI" Clicking on this does nothing.

I see in the extension logs for VSCode it got an error for the plugin: 

```
2023-04-14 21:04:30.304 [error] [Extension Host] Error: Binary request timed out. {"State":{}}
	at Timeout._onTimeout (/home/myusername/.vscode/extensions/tabnine.tabnine-vscode-3.6.44/out/extension.js:17:33113)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
```

though I didn't see any errors on installation.

I'm re-installing the plugin for VSCode (and ran it via commandline with `code --verbose`).  This seems to give me

```
[25706:0414/212128.489191:INFO:CONSOLE(2)] "Error: Request failed with status code 500", source: https://hub.tabnine.com/v9/static/js/main.f5d9f707.js (2)
[main 2023-04-14T19:21:28.669Z] menubarService#updateMenubar 1
```

on the console.

(When I try to get that js file from my browser it serves things, but returns `403`)

I do have Github copiliot installed as well on this editor, but it is disabled.

Any help to get this up and running would be appreciated. 

Thanks

**Comment by TzufTabnine** [comment]
Hi @Diederikjh 

Can you please send us the console log (Help->Console Developer Tools) after you try to sign in ( click on it in top right corner)

**Comment by Diederikjh** [comment]
There are lots of errors on the console:

```
Error: Request failed with status code 500
    at e.exports (hub.tabnine.com/v9/static/js/main.f5d9f707.js:2:25053)
    at e.exports (hub.tabnine.com/v9/static/js/main.f5d9f707.js:2:27489)
    at XMLHttpRequest.E (hub.tabnine.com/v9/static/js/main.f5d9f707.js:2:20336)
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
u @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
we @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
o @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
Promise.then (async)
we @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
a @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
Sme @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
fetchFn @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
l @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
u @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
t.fetch @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
n.executeFetch @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
n.fetch @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
n.refetch @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
t.onFocus @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
t.batch @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
n.onFocus @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
n.onFocus @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
(anonymous) @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
n @ hub.tabnine.com/v9/static/js/main.f5d9f707.js:2
```

When I open up the page for tabnine settings (and I don't do anything) I gets lots of these (they repeat every few seconds):

```
GET http://127.0.0.1:1123/sec-ltuteexkzkzavgwknhkz/user 404 (Not Found)
```


When I open the page initially I get:

```
main.f5d9f707.js:2          GET http://127.0.0.1:1123/sec-ltuteexkzkzavgwknhkz/country_iso_code 500 (Internal Server Error)
```

(My country code is ZA)

**Comment by avnerbarr** [comment]
Can you send me the logs from the tabnine engine itself - depending on how you have configured things it could be in a different location.

You can configure the log path in the `VSCode` settings by clicking the gear icon and in the search bar typing `tabnine`.

It should display a tabnine settings form:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/2404795/232417890-05a4a819-deda-4659-9c0c-1444819f6740.png">


<img width="757" alt="image" src="https://user-images.githubusercontent.com/2404795/232417959-293169c2-14db-4187-b970-ecf71bc4b727.png">


You can also search for the path in the terminal if you have issues by doing the  following:

find the running instance:

`ps -ef | grep -i tabnine`

We are looking for the log path which should appear after the argument:

```
--log-file-path /tmp/logavner-38063
```

Notice that each session will have a different log path. 

Try logging in to the hub. I would like to see errors that may be printed in the log for that session.

Thanks

**Comment by Diederikjh** [comment]
Sorry for only getting on this now:


Starts

```
ERROR [model_file_protocol::read] [2023-04-19:19:45:40 TabNine-deep-local ERROR] Failed to read header: Magic version mismatch
INFO [cpu_model::model_format] [2023-04-19:19:45:40 TabNine-deep-local INFO] No language mapping provided - falling back to default
INFO [models_api_singleton] [2023-04-19:19:45:40 TabNine INFO] Updated models API access token of user: None
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-19:19:45:40 TabNine INFO] New active private model: None
INFO [models_api_singleton] [2023-04-19:19:45:40 TabNine INFO] Waiting for access token to change...
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-19:19:45:40 TabNine INFO] sleeping for maximum of 3600s
INFO [ui::http_server] [2023-04-19:19:45:41 TabNine INFO] Started config server at 127.0.0.1:1123.
INFO [frontend::initialize] [2023-04-19:19:45:43 TabNine INFO] Hub site is: https://hub.tabnine.com/v9/?tabnineUrl=http://127.0.0.1:1123/sec-grottkwzqvpjrouplxyl
INFO [bootstrapper::bootstrapper_lib] [2023-04-19:19:45:45 TabNine INFO] current version is Some(Version { major: 4, minor: 4, patch: 284, pre: [], build: [] }), spawned version is Some(Version { major: 4, minor: 4, patch: 284, pre: [], build: [] }), remote version is Version { major: 4, minor: 4, patch: 284, pre: [], build: [] }
INFO [bootstrapper::bootstrapper_lib] [2023-04-19:19:45:45 TabNine INFO] don't need to upgrade
INFO [lunar_local::bridge] [2023-04-19:19:45:56 TabNine-deep-local INFO] Done loading model (took 16.34 seconds).
INFO [lunar_local::tune] [2023-04-19:19:45:56 TabNine-deep-local INFO] Selected 3 beams.
INFO [lunar_local::tune] [2023-04-19:19:45:56 TabNine-deep-local INFO] Selected context length of 160.
INFO [lunar_connection::local_lunar_connection] [2023-04-19:19:45:56 TabNine INFO] setting default model analytics
```

Settings open:

```
WARN [ui::http_server] [2023-04-19:19:46:33 TabNine WARN] Unknown request: OPTIONS event
INFO [ui::health_stale_checker] [2023-04-19:19:46:33 TabNine INFO] initializing hub health config watcher
ERROR [ui::http_server] [2023-04-19:19:46:33 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
ERROR [ui::http_server] [2023-04-19:19:46:33 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:46:33 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:46:33 TabNine ERROR] Cannot get status without a user
```

Click on sign in:


```
WARN [ui::http_server] [2023-04-19:19:47:14 TabNine WARN] Unknown request: OPTIONS event
INFO [auth::capabilities] [2023-04-19:19:47:14 TabNine INFO] Refresh now sender changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-19:19:47:14 TabNine INFO] Refreshing capabilities
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-19:19:47:14 TabNine INFO] pro advanced completions capabilities subscriber detected a change
ERROR [ui::http_server] [2023-04-19:19:47:14 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
ERROR [ui::http_server] [2023-04-19:19:47:14 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:14 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:14 TabNine ERROR] Cannot get status without a user
INFO [auth::capabilities] [2023-04-19:19:47:16 TabNine INFO] Refresh now sender changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-19:19:47:16 TabNine INFO] Refreshing capabilities
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-19:19:47:16 TabNine INFO] pro advanced completions capabilities subscriber detected a change
ERROR [ui::http_server] [2023-04-19:19:47:16 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
ERROR [ui::http_server] [2023-04-19:19:47:16 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:16 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:16 TabNine ERROR] Cannot get status without a user
INFO [auth::capabilities] [2023-04-19:19:47:18 TabNine INFO] Refresh now sender changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-19:19:47:18 TabNine INFO] Refreshing capabilities
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-19:19:47:18 TabNine INFO] pro advanced completions capabilities subscriber detected a change
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Cannot get status without a user
INFO [auth::capabilities] [2023-04-19:19:47:18 TabNine INFO] Refresh now sender changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-19:19:47:18 TabNine INFO] Refreshing capabilities
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-19:19:47:18 TabNine INFO] pro advanced completions capabilities subscriber detected a change
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:47:18 TabNine ERROR] Cannot get status without a user
```

Click on user icon -> Sign in with tabnine:

```
WARN [ui::http_server] [2023-04-19:19:48:11 TabNine WARN] Unknown request: OPTIONS event
INFO [auth::capabilities] [2023-04-19:19:48:11 TabNine INFO] Refresh now sender changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-19:19:48:11 TabNine INFO] Refreshing capabilities
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-19:19:48:11 TabNine INFO] pro advanced completions capabilities subscriber detected a change
ERROR [ui::http_server] [2023-04-19:19:48:11 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
ERROR [ui::http_server] [2023-04-19:19:48:11 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:48:11 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-19:19:48:11 TabNine ERROR] Cannot get status without a user

```

**Comment by avnerbarr** [comment]
could you provide the full log

**Comment by Diederikjh** [comment]
This is from a different session, but same behavior:

```
INFO [TabNine::main_utils] [2023-04-20:17:58:54 TabNine INFO] /home/diederik/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.284/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --log-file-path=/tmp/logavner-6027 --client-metadata clientVersion=1.77.3 pluginVersion=3.6.44 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=c3907d7b32083ee644559d6765fe4665cd8c75d587ff216c0b98892534982c58 vscode-is-new-app-install=false vscode-session-id=8deb3c16-ef67-48a4-98fe-08d5e73563f91682006314242 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true ide-restart-counter=0
INFO [global_config::config_migrations] [2023-04-20:17:58:55 TabNine INFO] Migrating configuration properties if necessary...
INFO [watchdog_api::wd_client] [2023-04-20:17:58:57 TabNine INFO] Initializing watchdog client...
INFO [watchdog_api::wd_client] [2023-04-20:17:58:57 TabNine INFO] Starting watchdog...
INFO [watchdog_api::wd_client] [2023-04-20:17:58:57 TabNine INFO] Starting watchdog...
INFO [TabNine::bootstrap_support] [2023-04-20:17:58:58 TabNine INFO] trying to start tabnine version Some("4.4.284")
INFO [TabNine::bootstrap_support] [2023-04-20:17:58:58 TabNine INFO] spawning tabnine with args ["/home/diederik/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.284/x86_64-unknown-linux-musl/TabNine", "--client=vscode", "--no-lsp=true", "--log-file-path=/tmp/logavner-6027", "--client-metadata", "clientVersion=1.77.3", "pluginVersion=3.6.44", "t9-vscode-AutoImportEnabled=true", "t9-vscode-TSAutoImportEnabled=true", "t9-vscode-JSAutoImportEnabled=true", "vscode-telemetry-enabled=true", "vscode-remote=false", "vscode-remote-name=undefined", "vscode-extension-kind=1", "vscode-theme-name=Default Dark+", "vscode-theme-kind=Dark", "vscode-machine-id=c3907d7b32083ee644559d6765fe4665cd8c75d587ff216c0b98892534982c58", "vscode-is-new-app-install=false", "vscode-session-id=8deb3c16-ef67-48a4-98fe-08d5e73563f91682006314242", "vscode-language=en", "vscode-app-name=Visual Studio Code", "vscode-beta-channel-enabled=false", "vscode-status-customization=unknown", "vscode-inline-api-enabled=true", "ide-restart-counter=0", "--no_bootstrap"]
INFO [TabNine::bootstrap_support] [2023-04-20:17:58:58 TabNine INFO] started tabnine process pid 7484 version Some("4.4.284"), desired version was Some("4.4.284") this version is Some("4.4.284")
INFO [TabNine::main_utils] [2023-04-20:17:58:58 TabNine INFO] /home/diederik/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.284/x86_64-unknown-linux-musl/TabNine --client=vscode --no-lsp=true --log-file-path=/tmp/logavner-6027 --client-metadata clientVersion=1.77.3 pluginVersion=3.6.44 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-remote-name=undefined vscode-extension-kind=1 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=c3907d7b32083ee644559d6765fe4665cd8c75d587ff216c0b98892534982c58 vscode-is-new-app-install=false vscode-session-id=8deb3c16-ef67-48a4-98fe-08d5e73563f91682006314242 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true ide-restart-counter=0 --no_bootstrap
INFO [watchdog_api::wd_client] [2023-04-20:17:58:58 TabNine INFO] Initializing watchdog client...
INFO [watchdog_api::wd_client] [2023-04-20:17:58:58 TabNine INFO] Starting watchdog...
INFO [frontend] [2023-04-20:17:58:58 TabNine INFO] LSP disabled
INFO [global_config::config_migrations] [2023-04-20:17:58:58 TabNine INFO] Migrating configuration properties if necessary...
INFO [recommend_tabnine_extension] [2023-04-20:17:58:59 TabNine INFO] registering recommender
INFO [recommend_tabnine_extension::vscode_recommended_extensions] [2023-04-20:17:58:59 TabNine INFO] not activating recommendation engine
INFO [models_api_singleton] [2023-04-20:17:58:59 TabNine INFO] Creating models api singleton...
ERROR [models_api_singleton] [2023-04-20:17:58:59 TabNine ERROR] Failed to create cache directory: File exists (os error 17)
INFO [models_api_singleton] [2023-04-20:17:58:59 TabNine INFO] Created models api client singleton.
INFO [lunar_connection::model_chooser] [2023-04-20:17:58:59 TabNine INFO] current private model is None
INFO [models_api_singleton] [2023-04-20:17:58:59 TabNine INFO] Waiting for access token to change...
INFO [models_api_singleton] [2023-04-20:17:58:59 TabNine INFO] Updating models API access token...
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:58:59 TabNine INFO] Starting private model update thread
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:58:59 TabNine INFO] Checking if private model changed
INFO [lunar_connection::model_chooser] [2023-04-20:17:58:59 TabNine INFO] using initial model ModelMetadata {
    model_id: "162640eb4381301da6ff3a6913c806965a2ec6a7d3a6943bec51de1088948c72",
    upload_time: 2021-05-25T15:38:00+00:00,
    crc32_over_file_without_headers: "ce94127b",
    model_size: Small,
    owned_by_team_id: None,
    specialized_for_language: None,
    source_type: None,
    display_name: None,
    is_production_ready: true,
    is_manually_selectable: false,
}
INFO [lunar_connection] [2023-04-20:17:58:59 TabNine INFO] lunar settings update thread started (Local(Public) ce94127b)
INFO [lunar_connection::local_lunar_connection] [2023-04-20:17:58:59 TabNine INFO] starting default model pre-loader DownloadSettings {
    api_key: None,
    meta_data_base_url: "https://api.tabnine.com",
    model: ModelMetadata {
        model_id: "162640eb4381301da6ff3a6913c806965a2ec6a7d3a6943bec51de1088948c72",
        upload_time: 2021-05-25T15:38:00+00:00,
        crc32_over_file_without_headers: "ce94127b",
        model_size: Small,
        owned_by_team_id: None,
        specialized_for_language: None,
        source_type: None,
        display_name: None,
        is_production_ready: true,
        is_manually_selectable: false,
    },
}
INFO [lunar_connection] [2023-04-20:17:58:59 TabNine INFO] lunar settings update thread started (Local(Public) ce94127b)
INFO [lunar_connection::project_model_override_installer] [2023-04-20:17:58:59 TabNine INFO] project model override feature is disabled
INFO [lunar_connection::model_chooser_connections] [2023-04-20:17:58:59 TabNine INFO] Started model connection config watcher loop.
INFO [lunar_connection] [2023-04-20:17:58:59 TabNine INFO] lunar settings update thread started (Remote cloud)
ERROR [models_api::models_api_client] [2023-04-20:17:58:59 TabNine ERROR] Failed to get models from cache. Error: No such file or directory (os error 2), Base cache directory: /home/diederik/.config/TabNine/models_api
INFO [auth::capabilities] [2023-04-20:17:58:59 TabNine INFO] User changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-20:17:58:59 TabNine INFO] Refreshing capabilities
INFO [lunar_connection::local_lunar_connection] [2023-04-20:17:58:59 TabNine INFO] running command "/home/diederik/.config/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.4.284/x86_64-unknown-linux-musl/TabNine-deep-local" "--settings" "/home/diederik/.config/TabNine/local.settingsce94127bSmall" "--settings-version" "1" "--log-file-path" "/tmp/logavner-6027" "--client" "vscode" "--client-metadata" "clientVersion=1.77.3" "pluginVersion=3.6.44" "t9-vscode-AutoImportEnabled=true" "t9-vscode-TSAutoImportEnabled=true" "t9-vscode-JSAutoImportEnabled=true" "vscode-telemetry-enabled=true" "vscode-remote=false" "vscode-remote-name=undefined" "vscode-extension-kind=1" "vscode-theme-name=Default Dark+" "vscode-theme-kind=Dark" "vscode-machine-id=c3907d7b32083ee644559d6765fe4665cd8c75d587ff216c0b98892534982c58" "vscode-is-new-app-install=false" "vscode-session-id=8deb3c16-ef67-48a4-98fe-08d5e73563f91682006314242" "vscode-language=en" "vscode-app-name=Visual Studio Code" "vscode-beta-channel-enabled=false" "vscode-status-customization=unknown" "vscode-inline-api-enabled=true" "ide-restart-counter=0"
INFO [frontend::initialize] [2023-04-20:17:58:59 TabNine INFO] Started.
INFO [global_config::config_migrations] [2023-04-20:17:58:59 TabNine-deep-local INFO] Migrating configuration properties if necessary...
INFO [TabNine_deep_local] [2023-04-20:17:58:59 TabNine-deep-local INFO] parsed settings are Some(Settings { cpu_model: CpuModelSettings { rate_limit_interval_seconds: None, rate_limit_amount: None, enable_power_saving_mode: false }, download: DownloadSettings { api_key: None, meta_data_base_url: "https://api.tabnine.com", model: ModelMetadata { model_id: "162640eb4381301da6ff3a6913c806965a2ec6a7d3a6943bec51de1088948c72", upload_time: 2021-05-25T15:38:00+00:00, crc32_over_file_without_headers: "ce94127b", model_size: Small, owned_by_team_id: None, specialized_for_language: None, source_type: None, display_name: None, is_production_ready: true, is_manually_selectable: false } }, tune: TuneSettings { enable_power_saving_mode: false, override_beams: None, override_context_length: None }, run: RunSettings { is_enabled: true, omit_prefix_suggestions: false, line_suggestions: false } })
INFO [TabNine_deep_local] [2023-04-20:17:58:59 TabNine-deep-local INFO] local_lock_path "/home/diederik/.config/TabNine/4.4.284/TabNine-deep-local.lockce94127b"
INFO [TabNine_deep_local] [2023-04-20:17:58:59 TabNine-deep-local INFO] using settings Settings { cpu_model: CpuModelSettings { rate_limit_interval_seconds: None, rate_limit_amount: None, enable_power_saving_mode: false }, download: DownloadSettings { api_key: None, meta_data_base_url: "https://api.tabnine.com", model: ModelMetadata { model_id: "162640eb4381301da6ff3a6913c806965a2ec6a7d3a6943bec51de1088948c72", upload_time: 2021-05-25T15:38:00+00:00, crc32_over_file_without_headers: "ce94127b", model_size: Small, owned_by_team_id: None, specialized_for_language: None, source_type: None, display_name: None, is_production_ready: true, is_manually_selectable: false } }, tune: TuneSettings { enable_power_saving_mode: false, override_beams: None, override_context_length: None }, run: RunSettings { is_enabled: true, omit_prefix_suggestions: false, line_suggestions: false } }
INFO [watchdog_api::wd_client] [2023-04-20:17:58:59 TabNine-deep-local INFO] Initializing watchdog client...
INFO [lunar_endpoints::local::server] [2023-04-20:17:59:00 TabNine-deep-local INFO] Got new local client connection 127.0.0.1:38578
INFO [lunar_local::bridge] [2023-04-20:17:59:00 TabNine-deep-local INFO] TabNine Local communication thread started.
INFO [lunar_local::bridge] [2023-04-20:17:59:00 TabNine-deep-local INFO] Loading model...
WARN [bootstrapper::register] [2023-04-20:17:59:00 TabNine WARN] server returned bad status code Ok(Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.tabnine.com")), port: None, path: "/experiments/register/v2", query: None, fragment: None }, status: 503, headers: {"content-length": "19", "content-type": "text/plain", "date": "Thu, 20 Apr 2023 15:59:00 GMT", "server": "istio-envoy", "vary": "Accept-Encoding", "x-envoy-upstream-service-time": "44", "strict-transport-security": "max-age=31536000; includeSubDomains"} })
WARN [bootstrapper::bootstrapper_lib] [2023-04-20:17:59:00 TabNine WARN] failed registering to server: with error Server
WARN [bootstrapper::bootstrapper_lib] [2023-04-20:17:59:00 TabNine WARN] user belongs to default experiment so calling cloud front server fallback
ERROR [model_file_protocol::read] [2023-04-20:17:59:00 TabNine-deep-local ERROR] Failed to read header: Magic version mismatch
INFO [cpu_model::model_format] [2023-04-20:17:59:00 TabNine-deep-local INFO] No language mapping provided - falling back to default
INFO [process_setup::command_ext] [2023-04-20:17:59:00 TabNine INFO] child exited with status exit status: 0
INFO [process_setup::command_ext] [2023-04-20:17:59:00 TabNine INFO] child exited with status exit status: 0
INFO [models_api_singleton] [2023-04-20:17:59:01 TabNine INFO] Updated models API access token of user: None
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:59:01 TabNine INFO] New active private model: None
INFO [models_api_singleton] [2023-04-20:17:59:01 TabNine INFO] Waiting for access token to change...
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:59:01 TabNine INFO] sleeping for maximum of 3600s
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:59:01 TabNine INFO] Checking if private model changed
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:59:01 TabNine INFO] New active private model: None
INFO [lunar_connection::connection_choosers::private_models::state] [2023-04-20:17:59:01 TabNine INFO] sleeping for maximum of 3600s
ERROR [analytics::send_queue] [2023-04-20:17:59:02 TabNine-deep-local ERROR] Failed to send analytics event, maximizing send backoff policy: Permanent(Error(Http(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("notify.tabnine.com")), port: None, path: "/notify/v1", query: None, fragment: None }, source: TimedOut }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }))
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-20:17:59:03 TabNine INFO] initializing pro advanced completions capabilities subscriber...
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-20:17:59:03 TabNine INFO] pro advanced completions capabilities subscriber detected a change
INFO [ui::http_server] [2023-04-20:17:59:03 TabNine INFO] Started config server at 127.0.0.1:1123.
INFO [frontend::initialize] [2023-04-20:17:59:04 TabNine INFO] Hub site is: https://hub.tabnine.com/v9/?tabnineUrl=http://127.0.0.1:1123/sec-lzdcixwrjsiqczlkwanr
INFO [lunar_local::bridge] [2023-04-20:17:59:06 TabNine-deep-local INFO] Done loading model (took 6.25 seconds).
INFO [lunar_local::tune] [2023-04-20:17:59:06 TabNine-deep-local INFO] Selected 2 beams.
INFO [lunar_local::tune] [2023-04-20:17:59:07 TabNine-deep-local INFO] Selected context length of 200.
INFO [lunar_connection::local_lunar_connection] [2023-04-20:17:59:07 TabNine INFO] setting default model analytics
WARN [ui::http_server] [2023-04-20:17:59:34 TabNine WARN] Unknown request: OPTIONS event
INFO [ui::health_stale_checker] [2023-04-20:17:59:34 TabNine INFO] initializing hub health config watcher
ERROR [ui::http_server] [2023-04-20:17:59:34 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
WARN [ui::http_server] [2023-04-20:17:59:35 TabNine WARN] Unknown request: OPTIONS event
WARN [ui::http_server] [2023-04-20:17:59:35 TabNine WARN] Unknown request: OPTIONS event
ERROR [ui::http_server] [2023-04-20:17:59:35 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-20:17:59:35 TabNine ERROR] Cannot get status without a user
ERROR [ui::http_server] [2023-04-20:17:59:35 TabNine ERROR] Cannot get status without a user
WARN [ui::http_server] [2023-04-20:17:59:35 TabNine WARN] Unknown request: OPTIONS event
WARN [ui::http_server] [2023-04-20:17:59:35 TabNine WARN] Unknown request: OPTIONS event
ERROR [ui::http_server] [2023-04-20:17:59:35 TabNine ERROR] Failed to fetch country ISO code: Error: No access token found
INFO [auth::capabilities] [2023-04-20:17:59:35 TabNine INFO] Refresh now sender changed. Refreshing capabilities
INFO [auth::capabilities] [2023-04-20:17:59:35 TabNine INFO] Refreshing capabilities
INFO [frontend::pro_advanced_completions_capabilities_listener] [2023-04-20:17:59:35 TabNine INFO] pro advanced completions capabilities subscriber detected a change
WARN [ui::http_server] [2023-04-20:17:59:43 TabNine WARN] Unknown request: OPTIONS event
```

**Comment by avnerbarr** [comment]
Thanks @Diederikjh for your assistance.

I'm wondering if there is some specific browser compatibility issue we are hitting and not aware of. 

1. Which browser are you using
2. Can you try to open the link in a different browser
3. When you open the hub you will notice a link similar to this (It could change): `https://hub.tabnine.com/v9/?tabnineUrl=http://127.0.0.1:1123/sec-grottkwzqvpjrouplxyl` . Could you copy-paste the argument for the `tabnineUrl=xxxx` in the browser in a new tab as well as in a different browser? In this example, it would be `http://127.0.0.1:1123/sec-grottkwzqvpjrouplxyl`.  
4. Make sure to provide us with the developer tool logs and the engine logs as you did here. 

I'm also tagging my colleagues who might have some additional insights.

@ofekby @yanir-codota 

Could you also take a look at this error?

Seems that the hub isn't loading properly.

**Comment by Diederikjh** [comment]
From the logs I see the URL is `INFO [frontend::initialize] [2023-04-23:10:03:12 TabNine INFO] Hub site is: https://hub.tabnine.com/v9/?tabnineUrl=http://127.0.0.1:1123/sec-fjswjbmmjkxisykuwfgp`

When I navigate to that URL (http://127.0.0.1:1123/sec-fjswjbmmjkxisykuwfgp) (using my default browser - Firefox (normal build nothing strange - except that I use the non-snap version of Firefox on my system - and I'm pretty sure VSCode is installed via snap)) it resolves the URL fine, and logging in, seems to work. 

Tabnine now says I'm on pro, so it looks good.

Thanks for the help.  

(Can I get an extra few days on my free trail please)

**Comment by TzufTabnine** [comment]
@Diederikjh 

We are glad to hear that. Please send an email to support@tabnine.com with your request (with the GitHub issue details) and we will extend your trial.

**Comment by Diederikjh** [comment]
Will do, thanks again
