### ISSUE TITLE
Exception in plugin Tabnine AI Code Completion - JS Java Python TS Rust Go PHP & More (1.0.37)

### ISSUE THREAD

**Issue by pdb159** [codota/TabNine#615]
**please complete the following information:**	
 - OS version: Linux Debian 	
 - Editor: PyCharm 2023.2 (Community Edition)
 - Editor version: Build #PC-232.8660.197 Runtime Version: 17.0.7+7-b1000.6 amd64
 - Programming language: Python 3.9.17
 - TabNine extension version: 1.0.37
 - Engine version (could be located within Tabnine Hub): 

**Issue Details:**

ava.lang.Throwable: Must be precomputed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.ui.scale.JBUIScale.computeSystemScaleFactor(JBUIScale.kt:188)
	at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:67)
	at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:66)
	at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
	at com.intellij.ui.scale.JBUIScale.sysScale(JBUIScale.kt:307)
	at com.intellij.ui.scale.ScaleContext.<init>(ScaleContext.kt:83)
	at com.intellij.ui.scale.ScaleContext$Companion.create(ScaleContext.kt:80)
	at com.intellij.ui.icons.CachedImageIcon.<init>(CachedImageIcon.kt:75)
	at com.intellij.ui.icons.CachedImageIcon.<init>(CachedImageIcon.kt:101)
	at com.intellij.ui.icons.ImageDataByPathLoader$Companion.createIcon(ImageDataByPathLoader.kt:63)
	at com.intellij.ui.icons.ImageDataByPathLoader$Companion.access$createIcon(ImageDataByPathLoader.kt:19)
	at com.intellij.ui.icons.ImageDataByPathLoader$Companion$findIconByPath$icon$1.invoke(ImageDataByPathLoader.kt:40)
	at com.intellij.ui.icons.ImageDataByPathLoader$Companion$findIconByPath$icon$1.invoke(ImageDataByPathLoader.kt:39)
	at com.intellij.ui.icons.ImageDataByPathLoader$Companion.findIconByPath$lambda$0(ImageDataByPathLoader.kt:39)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2685)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2683)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2666)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
	at com.intellij.ui.icons.ImageDataByPathLoader$Companion.findIconByPath(ImageDataByPathLoader.kt:39)
	at com.intellij.openapi.util.IconLoaderKt.findIconUsingNewImplementation(IconLoader.kt:501)
	at com.intellij.openapi.util.IconLoaderKt.findIconUsingNewImplementation$default(IconLoader.kt:500)
	at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.kt:195)
	at com.intellij.openapi.util.IconLoader.findIcon(IconLoader.kt:135)
	at com.tabnineCommon.general.StaticConfig.<clinit>(StaticConfig.java:56)
	at com.tabnineCommon.binary.fetch.LocalBinaryVersions.readActiveFile(LocalBinaryVersions.java:65)
	at com.tabnineCommon.binary.fetch.LocalBinaryVersions.activeVersion(LocalBinaryVersions.java:45)
	at com.tabnineCommon.binary.fetch.BootstrapperSupport.lambda$locateLocalBootstrapSupportedVersion$2(BootstrapperSupport.java:55)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at com.tabnineCommon.binary.fetch.BootstrapperSupport.locateLocalBootstrapSupportedVersion(BootstrapperSupport.java:53)
	at com.tabnineCommon.binary.fetch.BootstrapperSupport.bootstrapVersion(BootstrapperSupport.java:20)
	at com.tabnineCommon.binary.fetch.BinaryVersionFetcher.fetchBinary(BinaryVersionFetcher.java:38)
	at com.tabnineCommon.binary.BinaryRun.generateRunCommand(BinaryRun.java:36)
	at com.tabnineCommon.binary.BinaryProcessRequesterProvider.lambda$initProcess$1(BinaryProcessRequesterProvider.java:118)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

gz#25500<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/25500'>Zendesk ticket #25500</a>)</i>

**Comment by TzufTabnine** [comment]
Hi @pdb159,
We deployed a fix (version 1.0.38). Please update the new version and let us know if it works now.
