### ISSUE TITLE
Vscode becomes unresponsive for few seconds when i start a new instance or window

### ISSUE THREAD

**Issue by khanakia** [codota/TabNine#643]
**please complete the following information:**	
 - OS version: macos sonoma 14.2.1 ARM
 - Editor: vscode
 - Editor version:	Version: 1.87.2 (Universal)
 - Programming language: any
 - TabNine extension version: 4.140.0
 - Engine version (could be located within Tabnine Hub): 4.140.0

**Issue Details:**
Every time I start a new instance or new window of vscode i see `Tabning starting` as shown in the screenshot and it makes vscode unresponsive for a few seconds. It's slowing down my work a lot as I open and close vscode so many times a day.

This was not the case before but from 1 or 2 weeks I started facing the issue.

![Screenshot 2024-04-05 at 5 45 30 AM](https://github.com/codota/TabNine/assets/2174170/1a230bdd-c760-4e91-bd57-bd0ca0b32b32)

gz#30751<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/30751'>Zendesk ticket #30751</a>)</i>

**Comment by khanakia** [comment]
Check the videos here

With Tabnine enabled super slow: https://share.zight.com/jku8xd2B
With Tabning disabled: https://share.zight.com/6quX6Kmj

**Comment by TzufTabnine** [comment]
Hi @khanakia ,
Please send us the log files (devtools + engine) and a list of the installed extensions.

**Comment by khanakia** [comment]
Installed Extensions (not all the extensions are activated but I could find a way to export the only activated ones)
[installed extensions.txt](https://github.com/codota/TabNine/files/14979635/installed.extensions.txt)


Tabnine output
```
18:57:10 GMT+0530 (India Standard Time) [INFO]: spawning binary with command: /Volumes/D/khanakia/Library/Application Support/Code/User/globalStorage/tabnine.tabnine-vscode/binaries/4.144.0/aarch64-apple-darwin/TabNine args: --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.88.0 pluginVersion=3.90.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=false vscode-extension-kind=1 vscode-theme-name=Default Dark Modern vscode-theme-kind=Dark vscode-machine-id=b6490734901a5a7604325ee4b2bb17b3a22a68cff3c30f2298d8b4b6b3125d7b vscode-is-new-app-install=false vscode-session-id=4c64195a-b38c-4614-9f28-7131ad201b8d1713187625504 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 

18:57:10 GMT+0530 (India Standard Time) [DEBUG]: capabilities resolved immediately 

18:57:12 GMT+0530 (India Standard Time) [ERROR]: Error: Binary request timed out. {"State":{}} 

18:57:13 GMT+0530 (India Standard Time) [DEBUG]: Updating root paths for project analyzifygo_2024: ["/Volumes/D/www/projects/solverhood/analyzifygo_2024"] 
```

Devtools logs
```
 INFO Started local extension host with pid 53307.
9workbench.desktop.main.js:sourcemap:655   ERR [jinliming2.vscode-go-template]: 'configuration.semanticTokenType.description' must be defined and can not be empty
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/khanakia/Library/Application Support/Code/User for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/www/projects/solverhood/analyzifygo_2024/.vscode for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/khanakia/Library/Application Support/Code/User/settings.json for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/www/projects/solverhood/analyzifygo_2024/.vscode/settings.json for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/www/projects/solverhood/analyzifygo_2024/.vscode/launch.json for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/khanakia/Library/Application Support/Code/User/keybindings.json for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:152 [Extension Host] Congratulations, your extension "atlashcl" is now active!
workbench.desktop.main.js:sourcemap:152 [Extension Host] AtlasHCL Language Server starting...
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/khanakia/Library/Application Support/Code/User/snippets for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
12workbench.desktop.main.js:sourcemap:655  WARN [cmake-tools]: Couldn't find message for key cmake-tools.configuration.cmake.options.advanced.statusBarLength.description.
workbench.desktop.main.js:sourcemap:655  WARN [remote-ssh]: Couldn't find message for key setting.usseExecServer.description.
workbench.desktop.main.js:sourcemap:655  INFO [perf] Render performance baseline is 16ms
workbench.desktop.main.js:sourcemap:152 [Extension Host] installing vscgo: install -trimpath github.com/golang/vscode-go/vscgo@v0.41.2
workbench.desktop.main.js:sourcemap:655   ERR [Extension Host] failed to install vscgo - Error: Command failed: /usr/local/go/bin/go install -trimpath github.com/golang/vscode-go/vscgo@v0.41.2
go: cannot install cross-compiled binaries when GOBIN is set

workbench.desktop.main.js:sourcemap:152 [Extension Host] failed to install vscgo - Error: Command failed: /usr/local/go/bin/go install -trimpath github.com/golang/vscode-go/vscgo@v0.41.2
go: cannot install cross-compiled binaries when GOBIN is set

w @ workbench.desktop.main.js:sourcemap:152
$logExtensionHostMessage @ workbench.desktop.main.js:sourcemap:1623
S @ workbench.desktop.main.js:sourcemap:1623
Q @ workbench.desktop.main.js:sourcemap:1623
M @ workbench.desktop.main.js:sourcemap:1623
L @ workbench.desktop.main.js:sourcemap:1623
(anonymous) @ workbench.desktop.main.js:sourcemap:1623
y @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:89
fire @ workbench.desktop.main.js:sourcemap:628
q.onmessage @ workbench.desktop.main.js:sourcemap:1641
workbench.desktop.main.js:sourcemap:152 [Extension Host] Server: {
  "Commands": [
    "gopls.add_dependency",
    "gopls.add_import",
    "gopls.add_telemetry_counters",
    "gopls.apply_fix",
    "gopls.change_signature",
    "gopls.check_upgrades",
    "gopls.diagnose_files",
    "gopls.edit_go_directive",
    "gopls.fetch_vulncheck_result",
    "gopls.gc_details",
    "gopls.generate",
    "gopls.go_get_package",
    "gopls.list_imports",
    "gopls.list_known_packages",
    "gopls.maybe_prompt_for_telemetry",
    "gopls.mem_stats",
    "gopls.regenerate_cgo",
    "gopls.remove_dependency",
    "gopls.reset_go_mod_diagnostics",
    "gopls.run_go_work_command",
    "gopls.run_govulncheck",
    "gopls.run_tests",
    "gopls.start_debugging",
    "gopls.start_profile",
    "gopls.stop_profile",
    "gopls.test",
    "gopls.tidy",
    "gopls.toggle_gc_details",
    "gopls.update_go_sum",
    "gopls.upgrade_dependency",
    "gopls.vendor",
    "gopls.views",
    "gopls.workspace_stats"
  ],
  "Name": "gopls",
  "Version": "v0.15.2",
  "GoVersion": "go1.22.1"
}
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/www/projects/solverhood/analyzifygo_2024/.git for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR [File Watcher (node.js)] Refusing to watch /Volumes/D/www/projects/solverhood/analyzifygo_2024/.git/refs/remotes/origin/main for changes using fs.watch() for possibly being a network share where watching is unreliable and unstable.
workbench.desktop.main.js:sourcemap:655   ERR Cannot read properties of undefined (reading 'accessToken'): TypeError: Cannot read properties of undefined (reading 'accessToken')
    at b.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1693:21270)
    at b.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1693:22006)
    at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1693:21027)
workbench.desktop.main.js:sourcemap:152 [Extension Host] AtlasHCL Language Server started successfully
```

**Comment by TzufTabnine** [comment]
Hi,
Do you still have this issue?

**Comment by khanakia** [comment]
Yes i still having the issue

**Comment by TzufTabnine** [comment]
Hi @khanakia 
Please try to replicate the issue and send us the new logs -
https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode

**Comment by khanakia** [comment]
Please check the attached log files.

When opening a new vscode window i have to wait for few seconds to become my IDE active

[tabnine_rCURRENT.logs.txt](https://github.com/codota/TabNine/files/15311266/tabnine_rCURRENT.logs.txt)

**Comment by TzufTabnine** [comment]
We also need The Devtools console logs
Click Help->Toggle Developer Tools->Console
Can you tell us the email conected to your Tabnine accout? 
Can you send us a video of the issue?

**Comment by khanakia** [comment]
1. it's not connected to any email 

Check video once the tab nine is active only then my vscode becomes functional

https://github.com/codota/TabNine/assets/2174170/70195a20-3832-4ca1-a6ef-c0c0efd08c62

![Screenshot 2024-05-15 at 8 03 20 PM](https://github.com/codota/TabNine/assets/2174170/e7a7ee14-24f7-4f36-9ce3-a0d37d5fd698)

**Comment by TzufTabnine** [comment]
HI @khanakia 
Can you please update your plugin and see if that resolves the issue?

**Comment by khanakia** [comment]
Just updated to `3.102.0` and still same issue

Tabnine should not block the vscode on opening a new window

**Comment by khanakia** [comment]
It is working fine just reloaded the vscode. Thanks for fixing it
