### ISSUE TITLE
PHPStorm Plugin Exception Report

### ISSUE THREAD

**Issue by utoxin** [codota/TabNine#661]
**please complete the following information:**	
 - OS version: Win 11
 - Editor: PHPStorm
 - Editor version: PS-243.21565.133
 - Programming language: PHP
 - TabNine extension version: 1.162.0
 - Engine version (could be located within Tabnine Hub): 4.203.0-62

**Issue Details:**
PHPStorm reported the following error, and said to report it to you.

```
com.intellij.diagnostic.PluginException: ActionGroup should be registered using <group> tag: id="com.tabnine.actions.TabnineContextMenu" class="com.tabnine.chat.actions.TabnineContextMenu" [Plugin: com.tabnine.TabNine]
	at com.intellij.openapi.actionSystem.ActionStub.initAction(ActionStub.java:108)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.convertStub(ActionManagerImpl.kt:1714)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.getAction(ActionManagerImpl.kt:2198)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImplKt.access$getAction(ActionManagerImpl.kt:1)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.kt:411)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2.invokeSuspend(ActionAsyncProvider.kt:378)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2.invoke(ActionAsyncProvider.kt)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$loadAction$2.invoke(ActionAsyncProvider.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider.loadAction(ActionAsyncProvider.kt:377)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider.access$loadAction(ActionAsyncProvider.kt:35)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1$1.emit(Emitters.kt:220)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$filter$1$2.emit(Emitters.kt:219)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$mapNotNull$1$2.emit(Emitters.kt:223)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:114)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$mapNotNull$1.collect(SafeCollector.common.kt:112)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$filter$1.collect(SafeCollector.common.kt:112)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1.invokeSuspend(Emitters.kt:36)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1.invoke(Emitters.kt)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$unmatchedStubsFlow$$inlined$transform$1.invoke(Emitters.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperatorImpl.flowCollect(ChannelFlow.kt:191)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)


gz#36491<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/36491'>Zendesk ticket #36491</a>)</i>```

**Comment by TzufTabnine** [comment]
Can you please update your plugin and try again? It should be resolved now.
